#ifndef ErrorCode_H
#define ErrorCode_H

typedef enum{
	ERR_NO_ERROR,
	ERR_NUMBER_NOT_WELL_FORMED,
	ERR_ILLEGAL_ARGUMENT,
	ERR_EMPTY_ARGUMENT,
	ERR_NO_ARGUMENT,
	ERR_EMPTY_OPERATOR,
	ERR_INVALID_OPERATOR,
	ERR_UNKNOWN_INFIX_OPERATOR,
	ERR_UNKNOWN_PREFIX_OPERATOR,
	ERR_CANNOT_CONVERT_TO_PREFIX,
	ERR_INVALID_TOKEN_TYPE
} ErrorCode;


#endif //ErrorCode_H